---

# Parameter:  users: []

- name: Generate SSH key
  user:
    name: "{{ item }}"
    generate_ssh_key: yes
  with_items: "{{ users }}"
  when: "'masters' in group_names"

- name: trust masters
  include_tasks: trust_a_host.yml users={{ spark_users }} trustee={{ master_item }}
  with_items: "{{ groups['masters'] }}"
  loop_control:
    loop_var: master_item

# - name: Read pub key
#   shell: cat /home/{{ item }}/.ssh/id_rsa.pub
#   register: pub_key_content
#   with_items: "{{ users }}"
#   delegate_to: "{{ groups['masters'][0] }}"
#   become: true
#   run_once: true
#   changed_when: false

# - authorized_key: user={{ item.item }} key="{{ item.stdout }}"
#   with_items: "{{ pub_key_content.results }}"
