---

# Parameter:  users: []

- name: Generate SSH key
  user:
    name: "{{ item }}"
    generate_ssh_key: yes
  with_items: "{{ users }}"

- name: Trust localhost
  include_tasks: trust_a_host.yml trustee={{ inventory_hostname }}

# - name: Read pub key
#   shell: cat /home/{{ item }}/.ssh/id_rsa.pub
#   register: pub_key_content
#   with_items: "{{ users }}"
#   changed_when: false

# - authorized_key: user={{ item.item }} key="{{ item.stdout }}"
#   with_items: "{{ pub_key_content.results }}"
#   no_log: true
