---

- name: copy conf_editor
  copy: src='files/edit_conf/' dest="/edit_conf" owner={{ nobody }} group="{{ hadoop_conf.group }}" mode=0755 directory_mode=0755

- name: Present Config Directorys
  file:
    path: "/tmp/conf"
    owner: "{{ nobody }}"
    group: "{{ hadoop_conf.group }}"
    mode: 0775
    state: directory

- name: Setup single hadoop
  include_tasks: setup_hadoop_do.yml nodetype="Single" conftemplate="single.ini"
  when: not cluster_mode

- name: Setup namenode hadoop
  include_tasks: setup_hadoop_do.yml nodetype="Namenode" conftemplate="hdfs-namenode.ini"
  when: cluster_mode and is_namenode

- name: Setup datanode hadoop
  include_tasks: setup_hadoop_do.yml nodetype="Datanode" conftemplate="hdfs-datanode.ini"
  when: cluster_mode and is_datanode

- name: Setup Resourcemanager hadoop
  include_tasks: setup_hadoop_do.yml nodetype="Resourcemanager" conftemplate="yarn-resourcemanager.ini"
  when: cluster_mode and is_resource_mgr

- name: Setup Nodemanager hadoop
  include_tasks: setup_hadoop_do.yml nodetype="Nodemanager" conftemplate="yarn-nodemanager.ini"
  when: cluster_mode and is_node_mgr

- name: Setup Mapred hadoop
  include_tasks: setup_hadoop_do.yml nodetype="Mapred" conftemplate="mapred.ini"
  when: cluster_mode and ( is_mr_client or is_historyserver )

