---

# Parameter:  users: []
#             trustee: xxx

- name: Read users[{{ users | join(',') }}]' pub key from [{{ trustee }}]
  shell: cat /home/{{ item }}/.ssh/id_rsa.pub
  register: pub_key_content
  delegate_to: "{{ trustee }}"
  become: true
  changed_when: false
  with_items: "{{ users }}"
  run_once: true

- name: Trust users[{{ users | join(',') }}] from [{{ trustee }}]
  authorized_key: user={{ item_foo.item }} key="{{ item_foo.stdout }}"
  with_items: "{{ pub_key_content.results }}"
  loop_control:
    loop_var: item_foo
  no_log: true
