---

- name: stop firewalld service
  systemd: 
    name: firewalld
    enabled: no
    state: stopped
  ignore_errors: true

- name: stop ufw service
  service: 
    name: ufw
    enabled: no
    state: stopped
  ignore_errors: true

