---

- name: Configure YARN Cluster Mode
  block:
    - name: Update slaves
      block:
        - name: update yarn slaves
          include_tasks: _update_slaves.yml slaves={{ hadoop_nodes.node_mgrs }}
          when: inventory_hostname in hadoop_nodes.resource_mgrs

    - name: Setup Resourcemanager hadoop
      include_tasks: _setup_hadoop_do.yml nodetype="Resourcemanager" conftemplate="yarn-resourcemanager.ini"
      when: is_resource_mgr
    - name: Setup Nodemanager hadoop
      include_tasks: _setup_hadoop_do.yml nodetype="Nodemanager" conftemplate="yarn-nodemanager.ini"
      when: is_node_mgr
  when: inventory_hostname in hadoop_group_up.cluster

