---

- name: Launch standalone spark daemons
  block:
    - name: Run Standalone run-demo.sh
      raw: su - {{ spark_users[0] }} -l -c "{{ spark_conf.script_dir }}/run-demo.sh"
      when: is_spark_standalone_master
  when: standalone

- name: Launch on-yarn spark daemons
  block:
    - name: Run on-yarn run-demo.sh
      raw: su - {{ spark_users[0] }} -l -c "{{ spark_conf.script_dir }}/run-demo.sh"
      when: spark_run_demo | default(false)
  when: deploy_mode == 'yarn'
  